Make watcher skip moly points
angelolab/toffy pull request #117
Opened 2022-05-31 17:55 UTC by ackagel

Corrects issue #112 .

For a given scanCount in the run json, only `fov-{runOrder}-scan-{scanCount}` was expected, when all values ≥0 and ≤scanCount should be expected.  This was corrected so that all scans are expected.

Further, moly points are identified via the `"standardTarget"` field with value `"Molybdenum Foil"`, and added to a list.  All points are checked against this list, and if they are members, are properly skipped, without raising an error message.

2022-06-07 22:03 UTC, ngreenwald requested changes
Looks good, just needs a test case

2022-08-23 01:47 UTC, camisowers commented
Creates a combined run dir with both moly and regular fovs to test watcher on rather than using the tissue dir. Also removes the moly case testing from watcher_callbacks_test.py

2022-08-23 17:17 UTC, ngreenwald requested changes

2022-08-23 17:24 UTC, camisowers commented on toffy/fov_watcher_test.py
> +COMBINED_DATA_PATH = os.path.join(Path(__file__).parent, 'data', 'combined')
Not for watcher, but there are a few other test files that do. I can just rework those to use the combined directory.

2022-08-24 04:54 UTC, ngreenwald requested changes
Looks good, tests are failing

2022-08-24 20:55 UTC, ngreenwald approved these changes

2022-08-24 20:55 UTC, merged