Split run file
angelolab/toffy pull request #145
Opened 2022-07-12 23:10 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #144. Added a helper function to json_utils.py that splits the run json into smaller files for imaging. Also updated the notebooks to use the new function.

2022-07-14 23:22 UTC, ngreenwald requested changes
Looks good, just a few tweaks

2022-07-14 23:22 UTC, ngreenwald commented on toffy/json_utils.py
> +            "Sum of the provided list does not match the number of FOVs in the run file.")
Add a note saying what the sum and lengths are

2022-07-14 23:22 UTC, ngreenwald commented on toffy/json_utils_test.py
> +            assert os.path.exists(new_json)
This assert will never fail, if the file wasn't created then the previous line reading in the file will fail. I think it's fine to remove it

2022-07-14 23:22 UTC, ngreenwald commented on templates/2_create_tiled_mibi_run.ipynb
>    },
<p>Why is this cell needed?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/toffy/pull/145/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2022-07-14 23:22 UTC, ngreenwald commented on templates/2_create_tiled_mibi_run.ipynb
>    },
<p>This should default to reading in the tiled json that was just created above, not the original run file</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/toffy/pull/145/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2022-07-14 23:22 UTC, ngreenwald commented on templates/2_create_tma_mibi_run.ipynb
>      "# save remapped_fov_regions\n",
<p>Same comments as previous notebook</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/toffy/pull/145/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2022-07-18 18:30 UTC, ngreenwald requested changes
Great, and did you run the notebooks to make sure there's no syntax errors?

2022-07-18 19:07 UTC, camisowers commented
> Great, and did you run the notebooks to make sure there's no syntax errors?

Yes all good!

2022-07-18 21:19 UTC, ngreenwald approved these changes

2022-07-18 21:19 UTC, merged