Check voltage
angelolab/toffy pull request #148
Opened 2022-07-14 23:07 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #127. 

**How did you implement your changes**

Retrieve the detector voltage from each FOV json in the run and check whether it stays constant or changes. If not the same throughout, identify the FOV names and voltage values at each point of change in the run and print them in an error statement.

**Remaining issues**

If there are specific areas of your implementation that you feel need specific feedback, or if there are things you aren't sure about, please highlight them here

2022-07-15 20:48 UTC, ngreenwald requested changes
Looks good, just some more guidance to the user about what is being printed out would be helpful

2022-07-15 20:48 UTC, ngreenwald commented on toffy/normalize.py
> +        raise ValueError(f'Changes in detector voltage were found during '
This error message could use some more formatting.

2022-07-18 22:09 UTC, camisowers commented
> 
yep, works on the jsons in data/tissue and I just double checked it on a run from 6-13

2022-07-18 22:56 UTC, ngreenwald approved these changes

2022-07-18 22:56 UTC, merged