Update readme with directory structure
angelolab/toffy pull request #190
Opened 2022-08-02 18:42 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #170.

2022-08-02 20:39 UTC, camisowers commented
let me know if there's anything I should add!

2022-08-02 21:00 UTC, ngreenwald requested changes
Good start

2022-08-02 21:00 UTC, ngreenwald commented on README.md
> +- `normalization_curve`: directory which stores the normalization curve file for the machine that was produced by the [set up notebook](./templates/1_set_up_toffy.ipynb) and necessary for [notebook 4
Add a gif for how to pin to favorites within the finder window, and suggest the user pin the following folders:
tiled_image_jsons, autolabeled_jsons, run_metrics

2022-08-03 19:48 UTC, camisowers commented on README.md
> +## Directory structure
@srivarra I'll add the link to notebook 1, so you can merge PR #175 without it

2022-08-10 18:45 UTC, srivarra approved these changes
Looks good, I like the change of specifying the exact notebook `1_set_up_toffy.ipynb` instead of just saying the first notebook.

2022-08-10 20:07 UTC, ngreenwald requested changes
Looks good, just needs some more focusing to make it maximally useful

2022-08-10 20:07 UTC, ngreenwald commented on README.md
> +![alt text](templates/img/D_dirs.png)
We should have legends for all of the screenshots so that users know what they're supposed to be looking at

2022-08-10 20:07 UTC, ngreenwald commented on README.md
> +![alt text](templates/img/C_dirs.gif)
I think it's fine to have this just be a screenshot, rather than a GIF.

2022-08-10 20:07 UTC, ngreenwald commented on README.md
> +![alt text](templates/img/quick_access.gif)
This is too long. The GIFs should be like 6 seconds max. In addition, it doesn't actually show the shortcut popping up in the quick access section of the finder, so it's not helpful. 


This should show: The mouse moving to a folder, selecting quick access, having that folder pop up on the left sidebar, then clicking that folder on the sidebar

2022-08-12 19:06 UTC, ngreenwald approved these changes

2022-08-12 19:06 UTC, merged