Add workshop links to readme
angelolab/toffy pull request #260
Opened 2022-09-13 17:17 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #253.

2022-09-15 03:15 UTC, ngreenwald requested changes
Instead of just a link to the video, I would add a brief sentence saying that if they want more information about this, see the [video walkthrough]. Or something like that

2022-09-17 00:43 UTC, ngreenwald requested changes
Looks good. Did you click on all of the links in the draft version of the readme to make sure they work and point to the right video?

2022-09-17 01:59 UTC, camisowers commented
yep all good

2022-09-17 03:43 UTC, ngreenwald approved these changes

2022-09-17 03:43 UTC, merged