Add _pulse_height.csv file generation to watcher
angelolab/toffy pull request #262
Opened 2022-09-14 20:19 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #261. Adds pulse height file generation to the real-time monitoring notebook, to shorten the length of time it takes to normalize images in 4b.

**How did you implement your changes**

Create the FOV level callback `generate_pulse_heights` and implement in notebook 3a. Also add corresponding test cases and validation functions. 

**Remaining issues**

- [ ] clean up the test cases and variable names in `fov_watcher_test.py`

2022-09-17 00:35 UTC, ngreenwald commented on templates/3a_monitor_MIBI_run.ipynb
>     "source": [
<p>Add a description for what this callback does in the documentation above</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/toffy/pull/262/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2022-09-17 00:41 UTC, ngreenwald requested changes
Looks good. The reason the start and stop offsets are different is because for normalization, we want a narrow mass range. This ensures the MPH is only calculated from the ions that are actually metal ions, which are in the mass-deficient portion of the peak. 

The function defaults to +/- 0.5 because it was originally written for monitoring the run over time using 97, where everything is organics and it doesn't matter.

2022-09-20 00:55 UTC, ngreenwald requested changes
Looks good. Will you try out the actual watcher notebook with some bin files (can be generated already) to make sure everything works

2022-09-20 02:08 UTC, camisowers commented
> Looks good. Will you try out the actual watcher notebook with some bin files (can be generated already) to make sure everything works

All good!

2022-09-20 16:02 UTC, ngreenwald approved these changes

2022-09-20 16:03 UTC, merged