Compressed Tiff Files
angelolab/toffy pull request #280
Opened 2022-10-29 01:32 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #270. Adds compression to tiff files. Currently it uses the `zlib` the default of `skimage.external.tifffile`.

**How did you implement your changes**

Added a thin wrapper around `skimage.io.imsave` which contains the compression level and other extra arguments like `check_contrast`.
Replaced calls of `skimage.io.imsave` with `image_utils.save_image`. Uses the default `zlib` compression at level 6, as `lzma` is incompatible with the ImageJ family.

Here are the results for fov0 from the Example Dataset in Ark:

| Channel                | Original File Size Mb | Compressed File Size (Mb) | Compression Ratio |
|------------------------|-----------------------|---------------------------|-------------------|
| CD3.tiff               | 4.2M                  | 1.3M                      | 3.2:1             |
| CD4.tiff               | 4.2M                  | 2.2M                      | 1.9:1             |
| CD8.tiff               | 4.2M                  | 1.4M                      | 3.0:1             |
| CD14.tiff              | 4.2M                  | 1.7M                      | 2.5:1             |
| CD20.tiff              | 4.2M                  | 1.7M                      | 2.5:1             |
| CD31.tiff              | 4.2M                  | 490k                      | 8.6:1             |
| CD45.tiff              | 4.2M                  | 2.4M                      | 1.8:1             |
| CD68.tiff              | 4.2M                  | 1.1M                      | 3.8:1             |
| CD163.tiff             | 4.2M                  | 2.1M                      | 2.0:1             |
| CD163_nuc_exclude.tiff | 4.2M                  | 1.7M                      | 2.5:1             |
| CK17.tiff              | 4.2M                  | 1.2M                      | 3.5:1             |
| Collagen1.tiff         | 4.2M                  | 2.7M                      | 1.6:1             |
| ECAD.tiff              | 4.2M                  | 1.5M                      | 2.8:1             |
| ECAD_smoothed.tiff     | 4.2M                  | 3.9M                      | 1.1:1             |
| Fibronectin.tiff       | 4.2M                  | 2.9M                      | 1.4:1             |
| GLUT1.tiff             | 4.2M                  | 2.6M                      | 1.6:1             |
| H3K9ac.tiff            | 4.2M                  | 2.8M                      | 1.5:1             |
| H3K27me3.tiff          | 4.2M                  | 2.6M                      | 1.6:1             |
| HLADR.tiff             | 4.2M                  | 1.5M                      | 2.8:1             |
| IDO.tiff               | 4.2M                  | 845k                      | 5.0:1             |
| Ki67.tiff              | 4.2M                  | 1.8M                      | 2.3:1             |
| PD1.tiff               | 4.2M                  | 659k                      | 6.4:1             |
| SMA.tiff               | 4.2M                  | 1.3M                      | 3.2:1             |
| Vim.tiff               | 4.2M                  | 2.8M                      | 1.5:1             |

**Remaining issues**

None ATM.

2022-10-31 19:24 UTC, ngreenwald requested changes
Looks great! Really clean changes. 

1) Did you do a control-f or something to make sure these are all of the places where we do image saving? Are there are any in the notebooks that got missed?
2) The image extraction code uses the `mibi_bin_tools` functions to save TIFs. Can you open an issue in that repo and self-assign it? We can discuss tomorrow at the planning meeting when it makes the most sense to make that change, I think it can probably wait until this function is in TMI.

2022-10-31 19:24 UTC, ngreenwald commented on toffy/image_utils.py
> +def save_image(fname: Union[str, pathlib.Path], data: np.ndarray,
Nice, make sense to default all of the check_contrast flags into one function. This should get added to the list of things to put in TMI

2022-11-01 00:01 UTC, srivarra commented
Found one that I missed. Should be good to go now.

2022-11-01 01:19 UTC, ngreenwald approved these changes
Great, looks good

2022-11-01 01:19 UTC, merged