Turn on y ticks for QC plots
angelolab/toffy pull request #386
Opened 2023-06-30 22:19 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #378. QC plots need to have corresponding y-ticks because the scaling for each channel is different.

**How did you implement your changes**

Remove any setting in `visualize_qc_metrics` where `yticks` or `yticklabels` are set to `[]`.

2023-07-12 21:39 UTC, srivarra approved these changes

2023-07-12 23:15 UTC, camisowers approved these changes

2023-07-13 05:26 UTC, ngreenwald requested changes
What does the output look like now?

2023-07-13 20:20 UTC, alex-l-kong commented
@ngreenwald here's an example plot:

![Non-zero mean intensity_barplot_stats](https://github.com/angelolab/toffy/assets/31424707/42006ff6-f461-4410-9181-73f297d66d66)

2023-07-13 20:47 UTC, merged