Ensure runs below fovs_per_num threshold get skipped during Rosetta t…
angelolab/toffy pull request #406
Opened 2023-08-02 21:15 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #309. During Rosetta test set generation, sometimes the user will specify a `fovs_per_num` threshold that a few runs don't meet. This will cause the whole process to error out when in reality its fine that those runs don't make it in. If there are a lot of runs (sometimes over 100), it is cumbersome for the user to pick out which ones need to be removed.

To make things simple, just ensure that any runs that don't meet the `fovs_per_num` threshold in `copy_image_files`. Only if none of them do should we error out.

**How did you implement your changes**

Modify `copy_image_files` so that only a `warnings.warn` is thrown if some FOVs get skipped over. However, do keep the `ValueError` in case no runs get copied over.

**Remaining issues**

This doesn't exactly solve the issue of what happens if the user only ends up with a few valid runs out of several hundred due to a `fovs_per_run` that was unusually high. We might want to specify a percentage threshold for erroring out to account for this (ex. if fewer than 50% of `run_names` meet the threshold, error out and let the user know that the Rosetta results will not be indicative of the desired test set).

2023-08-02 21:59 UTC, camisowers requested changes
Looks good. Do you want to close #340 with this PR as well? I think I suggested it be handled by the rosetta v2 PR but that one seems to be held up.

2023-08-02 22:24 UTC, alex-l-kong commented
> Looks good. Do you want to close #340 with this PR as well? I think I suggested it to be handled by the rosetta v2 PR but that one seems to be held up.

Yeah I can address that one too.

2023-08-02 23:12 UTC, camisowers commented on src/toffy/rosetta.py
> +        print(f"Processing FOV {fovs[i]}")
Can probably just be "Processing fov-1-scan-1" instead of "Processing FOV fov-1-scan-1".

2023-08-02 23:42 UTC, camisowers approved these changes

2023-08-03 00:04 UTC, ngreenwald approved these changes
Looks fine, I don't think we need to keep track of how many runs are skipped since it's printed out for the user.

2023-08-03 00:04 UTC, merged