For autogain runs, add voltage plotting scheme
angelolab/toffy pull request #453
Opened 2023-11-01 21:43 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #445. Runs generated with autogain will have varying voltages per run, so `check_detector_voltage` should not run. Instead, the user should see a plot showing the voltage over acquisition order.

**How did you implement your changes**

A few changes will need to be made:

1. Add a watcher callback that generates this plot in real-time, in this way the user can track the autogain. This callback should be optional and not be specified if a notebook-defined `autogain` is not set
2. Provide a separate notebook that generates this plot post-run (similar to post-3a notebooks)
3. Remove the `check_detector_voltage` call if the `autogain` flag is set in the normalization notebook

2023-12-08 00:59 UTC, alex-l-kong commented
We've decided to update this PR to only include the plotting functionality inside the 4b normalization notebook. An `autogain` flag can be set to `True` to generate this plot as opposed to verifying that the voltage was consistent across the run.

2023-12-08 19:34 UTC, camisowers requested changes
Minor comments about using existing toffy functions.

2023-12-08 19:34 UTC, camisowers commented on src/toffy/normalize.py
> +        with open(json_file, "r") as f:
Could use json_utils.read_json_file() https://github.com/angelolab/toffy/blob/bdd0d6494e827c3f3f0bfb1fab076f02a4c259a3/src/toffy/json_utils.py#L96

2023-12-08 19:59 UTC, srivarra requested changes
Code looks good! What does this plot look like?

2023-12-08 21:30 UTC, alex-l-kong commented
> Code looks good! What does this plot look like?

The linked issue (#445) contains an example.

2023-12-08 21:32 UTC, srivarra approved these changes

2023-12-12 22:13 UTC, camisowers approved these changes
Nice!

2023-12-13 19:47 UTC, bryjcannon commented
From what I can tell things look good. 
The mibicontrol 1.8 warning is still present in the 4b notebook. You can remove this now, correct? Unsure if this is dependent on the other open PR dealing with autogain.

2023-12-13 20:01 UTC, alex-l-kong commented
> From what I can tell things look good. The mibicontrol 1.8 warning is still present in the 4b notebook. You can remove this now, correct? Unsure if this is dependent on the other open PR dealing with autogain.

Yeah I can remove it before merging. My thinking was this PR is going to be merged in first before the actual autogain support PR, so _technically_ full autogain support won't be there yet. But agree it's kind of confusing, let's nuke.

2023-12-13 20:16 UTC, bryjcannon approved these changes
Great job on this, and thanks!

2023-12-13 20:31 UTC, merged