Updating the License
angelolab/toffy pull request #47
Opened 2022-02-22 23:24 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Updates the license from the **Apache 2.0 License** to the **Modified Apache 2.0 License** found in [angelolab/ark-analysis](https://github.com/angelolab/ark-analysis/blob/master/LICENSE).

**How did you implement your changes**

Read through and changed the license to the **Modified Apache 2.0 License** for `angelolab/toffy`.

**Remaining issues**

None at the moment.

2022-02-22 23:43 UTC, ngreenwald requested changes
In the PR description, you need to explicitly says closes, close, fixes, fix etc right before referencing the issue for it to automatically close it, rather than just `in reference to issue #47'

2022-02-23 00:00 UTC, srivarra commented
@ngreenwald Oh I see. I've changed it to that format. How does it look now?

2022-02-23 00:26 UTC, alex-l-kong approved these changes
Looks good to me.

2022-02-23 00:49 UTC, ngreenwald approved these changes

2022-02-23 00:49 UTC, merged